# Generated by Django 3.2 on 2021-05-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('foto', models.FileField(upload_to='uploads')),
                ('b64', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
