# Generated by Django 3.2 on 2021-05-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captura',
            old_name='b64',
            new_name='json',
        ),
        migrations.AddField(
            model_name='captura',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
