# Generated by Django 3.2 on 2021-05-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210503_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captura',
            name='foto',
        ),
    ]
